language: python

python:
  - '2.7'

before_install:
  - pip install codecov

install:
  - pip install coverage
  - pip install matplotlib

script: 
  - python setup.py test
  - coverage run --source=magicmarc setup.py test

after_success:
  - codecov --token=feac69e4-4682-423a-9aba-8131fed441d3
