language: python

python:
  - '2.7'

before_install:
  - pip install codecov

after_success:
  - codecov

install:
  - pip install matplotlib

script: 
  - python setup.py test
  - codecov --token=feac69e4-4682-423a-9aba-8131fed441d3

